Feature/dswp 51 skip nav
bcgov/design-system-wordpress-plugin pull request #3
Opened 2024-11-15 17:21 UTC by ASpiteri-BCGov

2024-11-15 18:03 UTC, mhaswell-bcgov requested changes
Mostly concerned about the invalid HTML. The other comments are up to you whether to change.

2024-11-15 18:03 UTC, mhaswell-bcgov commented on src/Bcgov/DesignSystemPlugin/SkipNavigation.php
> +            $block_content = $html . $block_content;
Although this seems to work (not sure if it's the browser or WordPress that fixes it) it's producing invalid HTML:
`<nav id="main-navigation"<nav class="is-responsive order-1 md:order-0 wp-block-navigation is-layout-flex wp-block-navigation-is-layout-flex"` when I print `$block_content` out here.
I think we still need to do the regex replacement.

2024-11-15 18:48 UTC, mhaswell-bcgov requested changes

2024-11-15 18:48 UTC, mhaswell-bcgov commented on design-system-wordpress-plugin.php
> +$enque_scripts->init();
```suggestion
$enqueue_scripts->init();
```
Getting a critical error here. Can we fix the spelling of `enqueue` everywhere?

2024-11-16 00:12 UTC, mhaswell-bcgov commented on src/Bcgov/DesignSystemPlugin/SkipNavigation.php
> +        $main_content_added = false;
This was a class variable before wasn't it? I don't think it will work the same if it's defined inside the function.

2024-11-16 00:13 UTC, ASpiteri-BCGov commented on src/Bcgov/DesignSystemPlugin/SkipNavigation.php
> +        $main_content_added = false;
yea should I change it back?

2024-11-16 00:15 UTC, mhaswell-bcgov commented on src/Bcgov/DesignSystemPlugin/SkipNavigation.php
> +        $main_content_added = false;
Yeah, I think if you look at the page that has both a `<main>` and a page-content block it will have put the id on both of them with the variable stored here.

2024-11-16 00:32 UTC, mhaswell-bcgov approved these changes

2024-11-19 16:02 UTC, merged